version: '3.7'

services:
  snmppowermon:
    image: FROM ghcr.io/tiernano/snmppowermon:main
    env_file: snmppowermon.env
    volumes:
    - ./snmppowermon/data:/app/data
  nginx:
    image: nginx
    ports: 
      - "8888:80"
    volumes:
    - ./snmppowermon/data:/usr/share/nginx/html:ro

